'use strict';
const Voucher = require('../models/voucher');
const Patient = require('../models/patient');
const Commission = require('../models/commission');
const Transaction = require('../models/transaction');
const Service = require('../models/services');
const AccList = require('../models/accountingList');


async function handleCommission(data) {
  const voucherResult = await Voucher.findOne({ _id: data._id, isDeleted: false }).populate([
    { path: 'relatedPatient' },
    { path: 'referDoctor' },
    { path: 'testSelection.name' },
  ]);
  const totalRefer = calculateTotalRefer(voucherResult.testSelection);
  return totalRefer;
}

function calculateTotalRefer(testSelection) {
  let totalRefer = 0;
  testSelection.forEach((element) => {
    if (element.name && element.name.referAmount) {
      totalRefer += element.name.referAmount;
    }
  });
  return totalRefer;
}




exports.listAllVouchers = async (req, res) => {
  try {
    let result = await Voucher.find({ isDeleted: false }).populate([
      { path: 'relatedPatient' },
      { path: 'referDoctor' },
      { path: 'testSelection.name' },
    ])
    let count = await Voucher.find({ isDeleted: false }).count();
    res.status(200).send({
      success: true,
      count: count,
      data: result
    });
  } catch (error) {
    return res.status(500).send({ error: true, message: 'No Record Found!' });
  }
};


exports.getVoucher = async (req, res) => {
  const result = await Voucher.find({ _id: req.params.id, isDeleted: false }).populate([
    { path: 'relatedPatient' },
    { path: 'referDoctor' },
    { path: 'testSelection.name' },
  ])
  if (!result)
    return res.status(500).json({ error: true, message: 'No Record Found' });
  return res.status(200).send({ success: true, data: result[0] });
};

exports.getAutoGeneratedCode = async (req, res) => {
  let data = {}
  let today = new Date().toISOString()
  try {
    const pResult = await Patient.find({ _id: req.params.id })
    const latestDocument = await Voucher.find({}, { seq: 1 }).sort({ _id: -1 }).limit(1).exec();
    if (!latestDocument) return res.status(500).send({ error: true, message: error.message })
    if (latestDocument.length === 0) data = { ...data, seq: 1, voucherID: "VOU-" + pResult[0].patientID + "-" + today.split('T')[0].replace(/-/g, '') + "-1" } // if seq is undefined set initial patientID and seq
    if (latestDocument.length > 0) {
      const increment = latestDocument[0].seq + 1
      data = { ...data, voucherID: "VOU-" + pResult[0].patientID + "-" + today.split('T')[0].replace(/-/g, '') + "-" + increment, seq: increment }
    }
    return res.status(200).send({ success: true, data: data })
  } catch (error) {
    return res.status(500).send({ error: true, message: error.message })
  }
}

exports.createVoucher = async (req, res, next) => {
  let data = req.body;
  if (!data.relatedTransaction) {
    data.relatedTransaction = []; // Initialize the array if it doesn't exist
  }
  try {
    for (let i = 0; i < data.testSelection.length; i++) {
      const serviceResult = await Service.find({ _id: data.testSelection[i].name }).populate('relatedCategory')
      if (serviceResult[0].relatedCategory.relatedAccounting) {
        console.log(serviceResult[0].relatedCategory.relatedAccounting)
        var fTransResult = await Transaction.create(
          {
            "amount": data.testSelection[i].unitCharge,
            "date": Date.now(),
            "remark": "Lab Test Sales",
            "relatedAccounting": serviceResult[0].relatedCategory.relatedAccounting, //account
            "type": "Credit"
          }
        )
        data.relatedTransaction.push(fTransResult._id);
        const fromAccUpdate = await AccList.findOneAndUpdate(
          { _id: serviceResult[0].relatedCategory.relatedAccounting },
          { $inc: { amount: data.testSelection[i].unitCharge } },
          { new: true },
        );
      }
      
    }
    var secTransResult = await Transaction.create(
      {
        "amount": data.pay,
        "date": Date.now(),
        "remark": "Lab Test Sales",
        "relatedAccounting": req.body.relatedBank ? req.body.relatedBank : req.body.relatedCash,
        "relatedBank": req.body.relatedBank,
        "relatedCash": req.body.relatedCash,
        "type": "Debit"
      }
    );
    data.relatedTransaction.push(secTransResult._id);
    const toAccUpdate = await AccList.findOneAndUpdate(
      { _id: req.body.relatedBank ? req.body.relatedBank : req.body.relatedCash },
      { $inc: { amount: data.pay } },
      { new: true },
    );
    // Transaction )

    const newVoucher = new Voucher(data);
    const result = await newVoucher.save();
    const voucherResult = await Voucher.find({ _id: result._id }).populate([
      { path: 'relatedPatient' },
      { path: 'referDoctor' },
      { path: 'testSelection.name' },
    ])
    console.log(voucherResult)
    // handling commission
    const commissionResult = await handleCommission(result)
    const newCommission = new Commission({
      "relatedDoctor": req.body.referDoctor,
      "relatedVoucher": result._id,
      "totalCommission": commissionResult,
      "relatedPatient": req.body.relatedPatient
    })
    const commissionSave = await newCommission.save()
    // end of handleCommission
    const patientResult = await Patient.updateOne(
      { _id: req.body.patientID },
      { $push: { relatedVoucher: result._id } }
    )

    res.status(200).send({
      message: 'Voucher create success',
      success: true,
      data: result,
      patientData: patientResult,
      sTrans: secTransResult,
      commission: commissionSave
    });

  } catch (error) {
    return res.status(500).send({ "error": true, message: error.message })
  }
};

exports.updateVoucher = async (req, res, next) => {
  try {
    const result = await Voucher.findOneAndUpdate(
      { _id: req.body.id },
      req.body,
      { new: true },
    ).populate([
      { path: 'relatedPatient' },
      { path: 'referDoctor' },
      { path: 'testSelection.name' },
    ])
    return res.status(200).send({ success: true, data: result });
  } catch (error) {
    return res.status(500).send({ "error": true, "message": error.message })
  }
};

exports.updateRemarkAndResult = async (req, res, next) => {
  try {
    const result = await Voucher.updateOne(
      { "_id": req.body.voucherID, "testSelection._id": req.body.testSelectionID },
      { $set: { "testSelection.$.result": req.body.result, "testSelection.$.remark": req.body.remark } }
    ).populate('relatedPatient').populate('referDoctor').populate('testSelection.name')

    const statusResult = await checkStatus(req.body)

    const statusUpdate = await Voucher.findOneAndUpdate(
      { _id: req.body.voucherID },
      { $set: { status: statusResult } },
      { new: true },
    ).populate('relatedPatient').populate('referDoctor').populate('testSelection.name')
    return res.status(200).send({ success: true, data: statusUpdate });
  } catch (error) {
    return res.status(500).send({ "error": true, "message": error.message })
  }
};

exports.updateSubTest = async (req, res, next) => {
  try {
    const result = await Voucher.updateOne(
      { "_id": req.body.voucherID, "testSelection._id": req.body.testSelectionID },
      { $set: { "testSelection.$.subTest": req.body.subTest } }
    ).populate('relatedPatient').populate('referDoctor').populate('testSelection.name')

    // const result = await Service.findOneAndUpdate(
    //   {_id:req.body.testSelectionID},
    //   {$set:{subTest:req.body.subTest}},
    //   {new:true}
    // )
    // console.log(result)
    const statusResult = await checkStatus(req.body, res);

    const statusUpdate = await Voucher.findOneAndUpdate(
      { _id: req.body.voucherID },
      { $set: { status: statusResult } },
      { new: true },
    ).populate('relatedPatient').populate('referDoctor').populate('testSelection.name');

    return res.status(200).send({ success: true, data: statusUpdate });
  } catch (error) {
    console.log(error);
    return res.status(500).send({ "error": true, "message": error.message });
  }
};

async function checkStatus(data, res) {
  const statusResult = await Voucher.find({ "_id": data.voucherID, isDeleted: false })
    .populate('relatedPatient')
    .populate('referDoctor')
    .populate('testSelection.name');

  if (statusResult.length === 0) {
    throw new Error('No Record Found!');
  }

  const completedCount = statusResult[0].testSelection.filter(element => element.result).length;
  const totalCount = statusResult[0].testSelection.length;
  const status = completedCount === totalCount
    ? 'Finished'
    : completedCount === 0
      ? 'Pending'
      : 'In Progress';

  return status;
}


exports.deleteVoucher = async (req, res, next) => {
  try {
    const result = await Voucher.findOneAndUpdate(
      { _id: req.params.id },
      { isDeleted: true },
      { new: true },
    );
    return res.status(200).send({ success: true, data: { isDeleted: result.isDeleted } });
  } catch (error) {
    return res.status(500).send({ "error": true, "message": error.message })

  }
}

exports.activateVoucher = async (req, res, next) => {
  try {
    const result = await Voucher.findOneAndUpdate(
      { _id: req.params.id },
      { isDeleted: false },
      { new: true },
    );
    return res.status(200).send({ success: true, data: { isDeleted: result.isDeleted } });
  } catch (error) {
    return res.status(500).send({ "error": true, "message": error.message })
  }
};

exports.voucherPayment = async (req, res) => {
  try {
    let isPaid = false
    let { repayAmount, voucherID, repayDate, creditRemark } = req.body;
    const creditResult = await Voucher.find({ _id: voucherID }).populate('relatedPatient').populate('referDoctor').populate('testSelection.name')
    let leftover = creditResult[0].creditAmount - repayAmount
    if (leftover <= 0) {
      isPaid = true
    }
    if (isPaid === true) repayAmount = creditResult[0].creditAmount + creditResult[0].repayAmount
    const result = await Voucher.updateOne(
      { "_id": req.body.voucherID, },
      { $inc: { creditAmount: -repayAmount }, isPaid: isPaid, updatedAt: repayDate, creditRemark: creditRemark },
      { new: true }
    ).populate('relatedPatient').populate('referDoctor').populate('testSelection.name')
    if (result.length === 0) return res.status(404).send({ error: true, message: 'No Record Found!' })
    return res.status(200).send({ success: true, data: result })
  } catch (error) {
    return res.status(500).send({ "error": true, "message": error.message })
  }
}

exports.getRelatedVouchers = async (req, res) => {
  try {
    const { relatedPatient, referDoctor, date, status, start, end } = req.body;
    const query = { isDeleted: false };
    if (relatedPatient) query.relatedPatient = relatedPatient;
    if (referDoctor) query.referDoctor = referDoctor;
    if (date) query.date = date;
    if (status) query.status = status;
    if (start && end) query.date = { $gte: start, $lte: end }
    const result = await Voucher.find(query)
      .populate([
        { path: "relatedPatient" },
        { path: "referDoctor" },
        { path: "testSelection.name" },
      ])
      .exec();
    if (!result.length) {
      return res.status(404).json({
        success: false,
        message: "No related vouchers found.",
      });
    }
    return res.status(200).json({
      success: true,
      data: result,
    });
  } catch (err) {
    console.error(err);
    return res.status(500).json({
      success: false,
      message: "An error occurred while fetching related vouchers.",
    });
  }
};

exports.getTodaysVoucher = async (req, res) => {
  try {
    const result = await Voucher.find({ createdAt: { $gte: new Date(new Date().setHours("0", 0, 0)), $lt: new Date(new Date().setHours("23", 59, 59)) } }).populate([
      { path: 'relatedPatient' },
      { path: 'referDoctor' },
      { path: 'testSelection.name' },
    ])
    if (result.length === 0) return res.status(404).json({ error: true, message: 'No Record Found!' })
    return res.status(200).send({ success: true, data: result })
  } catch (error) {
    return res.status(500).send({ error: true, message: error.message })
  }
}

exports.filterVoucher = async (req, res) => {
  let totalCharge = 0
  let totalCredit = 0
  let totalCashdown = 0
  console.log(totalCharge, totalCredit, totalCashdown)
  let { start, end } = req.body;
  let query = { isDeleted: false }
  if (start && end) query.date = { $gte: start, $lte: end }
  const result = await Voucher.find(query).populate([
    { path: 'relatedPatient' },
    { path: 'referDoctor' },
    { path: 'testSelection.name' }
  ])
  result.map((e, i) => {
    totalCharge = e.totalCharge + totalCharge
    totalCredit = e.creditAmount + totalCredit
  })
  totalCashdown = totalCharge - totalCredit
  return res.status(200).send({ success: true, data: result, totalVoucher: totalCharge, totalCredit: totalCredit * (-1), totalCashdown: totalCashdown })
}

exports.getVouchersWithDoctorIDandTime = async (req, res) => {
  const { referDoctor, fromDate, toDate } = req.body;

  const result = await Voucher.aggregate([
    {
      $match: {
        referDoctor: referDoctor,
        isDeleted: false,
        createdAt: {
          $gte: new Date(fromDate),
          $lte: new Date(toDate)
        }
      }
    },
    {
      $group: {
        _id: null,
        totalAmount: { $sum: "$totalCharge" },
        vouchers: { $push: "$$ROOT" },
        count: { $sum: 1 }
      }
    },
    {
      $project: {
        _id: 0,
        totalAmount: 1,
        count: 1,
        data: "$vouchers"
      }
    }
  ]);
  if (result.length === 0) {
    return res.status(500).json({ success: false, message: 'No Record Found' });
  }

  const { totalAmount, count, data } = result[0];
  return res.status(200).json({
    success: true,
    count: count,
    data: data,
    totalAmount: totalAmount
  });
};
